

create table user2 (
       id bigint generated by default as identity,
        user_name varchar(50) not null,
        first_name varchar(30) not null,
        last_name varchar(20) not null,
        email varchar(200),
        primary key (id)
    );


create table admin_test(
    id bigint generated by default as identity,
    username varchar(20) not null,
    password varchar(100) not null,
    roles varchar(20) not null,
    refresh_token varchar(100),
    primary key (id)
);




create table member(
    id bigint generated by default as identity,
    email varchar(200),
    password varchar(200),
);

create table refresh_token_test(
    key varchar(100) ,
    value varchar(100),
    primary key (key)

);
alter table user2
       add constraint UK_user_user_name unique (user_name);
