DROP TABLE public.api;

CREATE TABLE public.api (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- id PK
	call_url varchar(200) NOT NULL, -- 호출 URL
	method_type varchar(20) NOT NULL, -- 요청 메소드 타입
	request_body_type varchar(20) NOT NULL, -- 요청 데이터 타입
	response_body_type varchar(20) NOT NULL, -- 응답 데이터 타입
	api_type varchar(20) NOT NULL, -- API 타입
	target_url varchar(150) NOT NULL, -- 목적지 URL
	target_path varchar(100) NOT NULL, -- 목적지 경로 / 서비스 URI
	content_type varchar(150) NOT NULL, -- 컨텐트 타입(header 정보)
	service_nm varchar(100) NOT NULL, -- 서비스명
	service_prefix varchar(50) NOT NULL, -- 서비스 prefix
	auth_info varchar(300) NULL, -- 권한 키(api key)
	CONSTRAINT api_pkey PRIMARY KEY (id)
);

ALTER TABLE public.api
    add constraint UK_Api_CallUrl unique (call_url);

COMMENT ON TABLE public.api IS 'API 목록';
-- Column comments
COMMENT ON COLUMN public.api.id IS 'id PK';
COMMENT ON COLUMN public.api.call_url IS '호출 URL';
COMMENT ON COLUMN public.api.method_type IS '요청 메소드 타입';
COMMENT ON COLUMN public.api.request_body_type IS '요청 데이터 타입';
COMMENT ON COLUMN public.api.response_body_type IS '응답 데이터 타입';
COMMENT ON COLUMN public.api.api_type IS 'API 타입';
COMMENT ON COLUMN public.api.target_url IS '목적지 URL';
COMMENT ON COLUMN public.api.target_path IS '목적지 경로 / 서비스 URI';
COMMENT ON COLUMN public.api.content_type IS '컨텐트 타입(header 정보)';
COMMENT ON COLUMN public.api.service_nm IS '서비스명';
COMMENT ON COLUMN public.api.service_prefix IS '서비스 prefix';
COMMENT ON COLUMN public.api.auth_info IS '권한 키(api key)';


DROP TABLE public.api_param;

CREATE TABLE public.api_param (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- id PK
	seq int4 NULL, -- 순번
	field_nm varchar(100) NOT NULL, -- 내부 필드명
	field_map_nm varchar(100) NOT NULL, -- 내부-외부 필드매핑명
	data_type varchar(20) NOT NULL, -- 데이터 타입
	required bool NOT NULL, -- 필수여부
	param_type varchar(50) NOT NULL, -- 파라미터 타입
	value varchar(200) NULL, -- 기본값
	description varchar(200) NULL, -- 설명
	api_id int8 NOT NULL, -- API ID
	CONSTRAINT api_param_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.api_param IS 'API 파라미터 목록';

-- Column comments

COMMENT ON COLUMN public.api_param.id IS 'id PK';
COMMENT ON COLUMN public.api_param.seq IS '순번';
COMMENT ON COLUMN public.api_param.field_nm IS '내부 필드명';
COMMENT ON COLUMN public.api_param.field_map_nm IS '내부-외부 필드매핑명';
COMMENT ON COLUMN public.api_param.data_type IS '데이터 타입';
COMMENT ON COLUMN public.api_param.required IS '필수여부';
COMMENT ON COLUMN public.api_param.param_type IS '파라미터 타입';
COMMENT ON COLUMN public.api_param.value IS '기본값';
COMMENT ON COLUMN public.api_param.description IS '설명';
COMMENT ON COLUMN public.api_param.api_id IS 'API ID';


DROP TABLE public.domain_dic;

CREATE TABLE public.domain_dic (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY, -- id PK
	type varchar(20) NOT NULL, -- 용어구분
	word_nm varchar(200)	 NOT NULL, -- 용어명
	word_eng_nm varchar(200) NOT NULL, -- 용어영문명
	word_abrv varchar(100) NOT NULL, -- 영문약어명
	CONSTRAINT domain_dic_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.domain_dic IS '도메인 사전';

-- Column comments

COMMENT ON COLUMN public.domain_dic.id IS 'id PK';
COMMENT ON COLUMN public.domain_dic.type IS '용어구분';
COMMENT ON COLUMN public.domain_dic.word_nm IS '용어명';
COMMENT ON COLUMN public.domain_dic.word_eng_nm IS '용어영문명';
COMMENT ON COLUMN public.domain_dic.word_abrv IS '영문명약어';

